spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: pedidos
    password: pedidos123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      repositories:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: auth-service
