server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/authdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:pedidos}
    password: ${SPRING_DATASOURCE_PASSWORD:pedidos123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

security:
  jwt:
    secret: ${JWT_SECRET:pedidos-ms-jwt-secret-key-2026-safe-token-01}
    expiration-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
